"""Q-chunking with a flow policy (QC-FQL) for Squint, ported from the official JAX `qc` repo
(agents/acfql.py, utils/networks.py, utils/datasets.py).

The policy outputs a chunk of `horizon` actions at once, generated by a flow-matching (BC) vector field.
For RL, the BC flow is distilled into a one-step policy that is trained to maximise Q of the *whole chunk*
(FQL). The critic is a scalar Q-ensemble over (obs, flattened action chunk) with an h-step TD backup.

Network wiring follows acfql.py: the critic, the BC flow and the one-step policy each own an image encoder
(trained only by that network's loss), the target critic is a full copy of the critic *including* its
encoder, the actor's Q term evaluates the (frozen) critic on its own encoder, and MLPs are
Dense -> GELU -> [LayerNorm] with Glorot-uniform init. Squint's CNN + Projection stands in for the
encoder since observations here are a 16x16 wrist image plus proprio state.

All actions live in the normalised [-1, 1] space; the training script converts to/from env units.
"""
import copy
from dataclasses import dataclass
from typing import Tuple

import torch
import torch.nn as nn

from train_squint import CNNEncoder, Projection


@dataclass
class QCConfig:
    horizon: int = 5
    """action chunk length h"""
    actor_type: str = "distill-ddpg"
    """'distill-ddpg' (one-step policy distilled from the flow, trained on Q) or 'best-of-n' (sample n flow chunks, argmax Q)"""
    actor_num_samples: int = 32
    """n for best-of-n"""
    flow_steps: int = 10
    """Euler steps when integrating the flow"""
    alpha: float = 100.0
    """weight of the distillation loss (BC coefficient, tune per task)"""
    hidden_dim: int = 512
    """hidden width of actor nets"""
    actor_layers: int = 4
    critic_hidden_dim: int = 512
    critic_layers: int = 4
    num_q: int = 2
    q_agg: str = "mean"
    """how to aggregate the ensemble for the TD target ('mean' or 'min')"""
    gamma: float = 0.99
    tau: float = 0.005
    lr: float = 3e-4


def _glorot(m):
    # acfql's default_init: variance_scaling(1.0, 'fan_avg', 'uniform') == Glorot uniform, zero bias
    if isinstance(m, nn.Linear):
        nn.init.xavier_uniform_(m.weight)
        nn.init.zeros_(m.bias)


class MLP(nn.Module):
    """acfql MLP: hidden layers are Dense -> GELU -> (LayerNorm), last layer is a plain Dense."""

    def __init__(self, in_dim, hidden_dim, n_layers, out_dim, layer_norm):
        super().__init__()
        layers, d = [], in_dim
        for _ in range(n_layers):
            layers += [nn.Linear(d, hidden_dim), nn.GELU()]
            if layer_norm:
                layers.append(nn.LayerNorm(hidden_dim))
            d = hidden_dim
        layers.append(nn.Linear(d, out_dim))
        self.net = nn.Sequential(*layers)
        self.net.apply(_glorot)

    def forward(self, x):
        return self.net(x)


class ObsEncoder(nn.Module):
    """Image + proprio -> flat feature (Squint's CNN encoder followed by its LayerNorm'd projection)."""

    def __init__(self, n_obs, n_state):
        super().__init__()
        self.cnn = CNNEncoder(n_obs=n_obs)
        self.proj = Projection(self.cnn.repr_dim, n_state)
        self.out_dim = self.proj.repr_dim

    def forward(self, rgb, state):
        return self.proj(self.cnn(rgb), state)


class FlowVectorField(nn.Module):
    """v_theta(obs, a_t, t) over the flattened action chunk (acfql ActorVectorField, no layer norm)."""

    def __init__(self, n_obs, n_state, chunk_dim, hidden_dim, n_layers, with_time=True):
        super().__init__()
        self.encoder = ObsEncoder(n_obs, n_state)
        self.with_time = with_time
        self.net = MLP(self.encoder.out_dim + chunk_dim + int(with_time), hidden_dim, n_layers, chunk_dim,
                       layer_norm=False)

    def encode(self, rgb, state):
        return self.encoder(rgb, state)

    def forward_encoded(self, feat, actions, t=None):
        x = [feat, actions] if t is None else [feat, actions, t]
        return self.net(torch.cat(x, dim=-1))

    def forward(self, rgb, state, actions, t=None):
        return self.forward_encoded(self.encode(rgb, state), actions, t)


class EnsembleLinear(nn.Module):
    def __init__(self, num, in_dim, out_dim):
        super().__init__()
        self.weight = nn.Parameter(torch.empty(num, in_dim, out_dim))
        self.bias = nn.Parameter(torch.zeros(num, 1, out_dim))
        for w in self.weight.data:
            nn.init.xavier_uniform_(w)

    def forward(self, x):  # x: [num, B, in]
        return torch.baddbmm(self.bias, x, self.weight)


class ChunkCritic(nn.Module):
    """acfql Value: shared encoder, then a Q-ensemble MLP (Dense -> GELU -> LayerNorm) on
    [features, flat action chunk] -> [num_q, B]."""

    def __init__(self, n_obs, n_state, chunk_dim, hidden_dim, n_layers, num_q):
        super().__init__()
        self.num_q = num_q
        self.encoder = ObsEncoder(n_obs, n_state)
        layers, d = [], self.encoder.out_dim + chunk_dim
        for _ in range(n_layers):
            layers += [EnsembleLinear(num_q, d, hidden_dim), nn.GELU(), nn.LayerNorm(hidden_dim)]
            d = hidden_dim
        layers.append(EnsembleLinear(num_q, d, 1))
        self.net = nn.Sequential(*layers)

    def forward_encoded(self, feat, actions):
        x = torch.cat([feat, actions], dim=-1)
        return self.net(x.unsqueeze(0).expand(self.num_q, -1, -1)).squeeze(-1)

    def forward(self, rgb, state, actions):
        return self.forward_encoded(self.encoder(rgb, state), actions)


class QCAgent(nn.Module):
    def __init__(self, cfg: QCConfig, n_obs: Tuple[int, int, int], n_state: int, n_act: int, device):
        super().__init__()
        self.cfg = cfg
        self.n_act = n_act
        self.chunk_dim = n_act * cfg.horizon

        self.critic = ChunkCritic(n_obs, n_state, self.chunk_dim, cfg.critic_hidden_dim, cfg.critic_layers, cfg.num_q)
        self.critic_target = copy.deepcopy(self.critic)  # includes the encoder, as in acfql
        self.critic_target.requires_grad_(False)
        self.bc_flow = FlowVectorField(n_obs, n_state, self.chunk_dim, cfg.hidden_dim, cfg.actor_layers)
        self.onestep = FlowVectorField(n_obs, n_state, self.chunk_dim, cfg.hidden_dim, cfg.actor_layers,
                                       with_time=False)
        self.to(device)

        self.critic_opt = torch.optim.Adam(self.critic.parameters(), lr=cfg.lr)
        actor_params = list(self.bc_flow.parameters())
        if cfg.actor_type == "distill-ddpg":
            actor_params += list(self.onestep.parameters())
        self.actor_opt = torch.optim.Adam(actor_params, lr=cfg.lr)

    # ------------------------------------------------------------------ acting
    def compute_flow_actions(self, rgb, state, noise):
        """Euler-integrate the BC flow from noise (t=0) to an action chunk (t=1)."""
        feat = self.bc_flow.encode(rgb, state)
        a = noise
        n = self.cfg.flow_steps
        for i in range(n):
            t = torch.full((*a.shape[:-1], 1), i / n, device=a.device)
            a = a + self.bc_flow.forward_encoded(feat, a, t) / n
        return a.clamp(-1, 1)

    @torch.no_grad()
    def sample_actions(self, rgb, state, deterministic=False):
        """Flattened action chunk [B, h * n_act] in normalised action space. `deterministic` feeds the
        one-step policy zero noise (the mean of its noise input), for evaluation."""
        B = rgb.shape[0]
        if self.cfg.actor_type == "distill-ddpg":
            noise = torch.randn(B, self.chunk_dim, device=rgb.device)
            if deterministic:
                noise.zero_()
            return self.onestep(rgb, state, noise).clamp(-1, 1)
        # best-of-n: draw n flow chunks per obs, keep the one with the highest aggregated Q
        n = self.cfg.actor_num_samples
        noise = torch.randn(B * n, self.chunk_dim, device=rgb.device)
        r, s = rgb.repeat_interleave(n, 0), state.repeat_interleave(n, 0)
        acts = self.compute_flow_actions(r, s, noise)
        qs = self.critic(r, s, acts)
        q = qs.mean(0) if self.cfg.q_agg == "mean" else qs.min(0).values
        best = q.view(B, n).argmax(1)
        return acts.view(B, n, -1)[torch.arange(B, device=q.device), best]

    @torch.no_grad()
    def act(self, rgb, state, deterministic=False):
        """Full chunk [B, horizon, n_act] in normalised action space."""
        return self.sample_actions(rgb, state, deterministic).view(-1, self.cfg.horizon, self.n_act)

    # ---------------------------------------------------------------- learning
    def update(self, b, update_actor=True):
        """One gradient step on critic + actor from the same batch (acfql total_loss). `b` comes from
        ChunkBuffer.sample (see qc_data.py)."""
        cfg = self.cfg
        B = b["actions"].shape[0]
        actions = b["actions"].reshape(B, -1)

        # ---- critic: h-step TD on the flattened chunk
        with torch.no_grad():
            next_a = self.sample_actions(b["next_rgb"], b["next_state"])
            nq = self.critic_target(b["next_rgb"], b["next_state"], next_a)
            next_q = nq.mean(0) if cfg.q_agg == "mean" else nq.min(0).values
            target = b["rewards"] + (cfg.gamma ** cfg.horizon) * b["masks"] * next_q
        q = self.critic(b["rgb"], b["state"], actions)
        critic_loss = (((q - target.unsqueeze(0)) ** 2) * b["critic_valid"].unsqueeze(0)).mean()

        info = dict(critic_loss=critic_loss.detach(), q_mean=q.detach().mean(), q_max=q.detach().max(),
                    q_min=q.detach().min())
        actor_loss = None
        if update_actor:
            actor_loss, actor_info = self._actor_loss(b, actions)
            info.update(actor_info)

        # acfql takes one step on critic_loss + actor_loss w.r.t. the same parameters; the actor's Q term
        # must not move the critic, which _actor_loss guarantees by freezing it.
        self.critic_opt.zero_grad(set_to_none=True)
        self.actor_opt.zero_grad(set_to_none=True)
        (critic_loss if actor_loss is None else critic_loss + actor_loss).backward()
        self.critic_opt.step()
        if actor_loss is not None:
            self.actor_opt.step()
        with torch.no_grad():
            torch._foreach_lerp_(list(self.critic_target.parameters()), list(self.critic.parameters()), cfg.tau)
        return info

    def _actor_loss(self, b, actions):
        cfg = self.cfg
        rgb, state = b["rgb"], b["state"]
        B = actions.shape[0]

        # flow-matching BC loss on the dataset/replay chunk; only on valid chunk steps
        x0 = torch.randn_like(actions)
        t = torch.rand(B, 1, device=actions.device)
        xt = (1 - t) * x0 + t * actions
        vel = actions - x0
        pred = self.bc_flow(rgb, state, xt, t)
        bc_loss = (((pred - vel) ** 2).view(B, cfg.horizon, self.n_act) * b["valid"].unsqueeze(-1)).mean()

        if cfg.actor_type == "distill-ddpg":
            noise = torch.randn(B, self.chunk_dim, device=actions.device)
            with torch.no_grad():
                target_a = self.compute_flow_actions(rgb, state, noise)
            a_pi = self.onestep(rgb, state, noise)
            distill = ((a_pi - target_a) ** 2).mean()
            self.critic.requires_grad_(False)  # gradient only flows into the actions
            q = self.critic(rgb, state, a_pi.clamp(-1, 1)).mean(0)
            self.critic.requires_grad_(True)
            q_loss = -q.mean()
        else:
            distill = q_loss = torch.zeros((), device=actions.device)

        loss = bc_loss + cfg.alpha * distill + q_loss
        return loss, dict(actor_loss=loss.detach(), bc_flow_loss=bc_loss.detach(), distill_loss=distill.detach(),
                          q_loss=q_loss.detach())

    def state_dicts(self):
        return dict(critic=self.critic.state_dict(), critic_target=self.critic_target.state_dict(),
                    bc_flow=self.bc_flow.state_dict(), onestep=self.onestep.state_dict())

    def load_state_dicts(self, ckpt):
        for k in ("critic", "critic_target", "bc_flow", "onestep"):
            getattr(self, k).load_state_dict(ckpt[k])
