"""Q-chunking with a flow policy (QC-FQL) for Squint, ported from the official JAX `qc` repo
(agents/acfql.py, utils/networks.py, utils/datasets.py).

The policy outputs a chunk of `horizon` actions at once, generated by a flow-matching (BC) vector field.
For RL, the BC flow is distilled into a one-step policy that is trained to maximise Q of the *whole chunk*
(FQL). The critic is a scalar Q-ensemble over (obs, flattened action chunk) with an h-step TD backup.

The losses follow acfql.py exactly. The image pipeline follows Squint instead of acfql's one-encoder-per-
network: a single CNN encoder is trained by the critic loss and the actors read its detached features (as
in Squint/DrQ), each network keeping its own LayerNorm'd projection. With 16x16 wrist images this is
Squint's proven setup, and it runs the CNN twice per update instead of ~7 times. MLPs are acfql's
Dense -> GELU -> [LayerNorm] with Glorot-uniform init.

All actions live in the normalised [-1, 1] space; the training script converts to/from env units.
"""
import copy
from dataclasses import dataclass
from typing import Tuple

import torch
import torch.nn as nn

from train_squint import CNNEncoder, Projection


@dataclass
class QCConfig:
    horizon: int = 5
    """action chunk length h"""
    actor_type: str = "distill-ddpg"
    """'distill-ddpg' (one-step policy distilled from the flow, trained on Q) or 'best-of-n' (sample n flow chunks, argmax Q)"""
    actor_num_samples: int = 32
    """n for best-of-n"""
    flow_steps: int = 10
    """Euler steps when integrating the flow"""
    alpha: float = 100.0
    """weight of the distillation loss (BC coefficient, tune per task)"""
    hidden_dim: int = 256
    actor_layers: int = 3
    critic_hidden_dim: int = 256
    critic_layers: int = 3
    num_q: int = 2
    q_agg: str = "mean"
    """how to aggregate the ensemble for the TD target ('mean' or 'min')"""
    gamma: float = 0.9
    tau: float = 0.01
    lr: float = 3e-4


def _glorot(m):
    # acfql's default_init: variance_scaling(1.0, 'fan_avg', 'uniform') == Glorot uniform, zero bias
    if isinstance(m, nn.Linear):
        nn.init.xavier_uniform_(m.weight)
        nn.init.zeros_(m.bias)


class MLP(nn.Module):
    """acfql MLP: hidden layers are Dense -> GELU -> (LayerNorm), last layer is a plain Dense."""

    def __init__(self, in_dim, hidden_dim, n_layers, out_dim, layer_norm):
        super().__init__()
        layers, d = [], in_dim
        for _ in range(n_layers):
            layers += [nn.Linear(d, hidden_dim), nn.GELU()]
            if layer_norm:
                layers.append(nn.LayerNorm(hidden_dim))
            d = hidden_dim
        layers.append(nn.Linear(d, out_dim))
        self.net = nn.Sequential(*layers)
        self.net.apply(_glorot)

    def forward(self, x):
        return self.net(x)


class FlowVectorField(nn.Module):
    """v_theta(obs, a_t, t) over the flattened action chunk (acfql ActorVectorField, no layer norm).
    Takes CNN features; with_time=False gives the one-step policy (obs, noise) -> chunk."""

    def __init__(self, rgb_repr_dim, n_state, chunk_dim, hidden_dim, n_layers, with_time=True):
        super().__init__()
        self.proj = Projection(rgb_repr_dim, n_state)
        self.with_time = with_time
        self.net = MLP(self.proj.repr_dim + chunk_dim + int(with_time), hidden_dim, n_layers, chunk_dim,
                       layer_norm=False)

    def project(self, rgb_feat, state):
        return self.proj(rgb_feat, state)

    def forward_projected(self, z, actions, t=None):
        return self.net(torch.cat([z, actions] if t is None else [z, actions, t], dim=-1))

    def forward(self, rgb_feat, state, actions, t=None):
        return self.forward_projected(self.project(rgb_feat, state), actions, t)


class EnsembleLinear(nn.Module):
    def __init__(self, num, in_dim, out_dim):
        super().__init__()
        self.weight = nn.Parameter(torch.empty(num, in_dim, out_dim))
        self.bias = nn.Parameter(torch.zeros(num, 1, out_dim))
        for w in self.weight.data:
            nn.init.xavier_uniform_(w)

    def forward(self, x):  # x: [num, B, in]
        return torch.baddbmm(self.bias, x, self.weight)


class ChunkCritic(nn.Module):
    """acfql Value head on CNN features: projection, then a Q-ensemble MLP (Dense -> GELU -> LayerNorm)
    on [features, flat action chunk] -> [num_q, B]."""

    def __init__(self, rgb_repr_dim, n_state, chunk_dim, hidden_dim, n_layers, num_q):
        super().__init__()
        self.num_q = num_q
        self.proj = Projection(rgb_repr_dim, n_state)
        layers, d = [], self.proj.repr_dim + chunk_dim
        for _ in range(n_layers):
            layers += [EnsembleLinear(num_q, d, hidden_dim), nn.GELU(), nn.LayerNorm(hidden_dim)]
            d = hidden_dim
        layers.append(EnsembleLinear(num_q, d, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, rgb_feat, state, actions):
        x = torch.cat([self.proj(rgb_feat, state), actions], dim=-1)
        return self.net(x.unsqueeze(0).expand(self.num_q, -1, -1)).squeeze(-1)


class QCAgent(nn.Module):
    def __init__(self, cfg: QCConfig, n_obs: Tuple[int, int, int], n_state: int, n_act: int, device):
        super().__init__()
        self.cfg = cfg
        self.n_act = n_act
        self.chunk_dim = n_act * cfg.horizon

        self.encoder = CNNEncoder(n_obs=n_obs)  # shared; trained by the critic loss only (Squint)
        d = self.encoder.repr_dim
        self.critic = ChunkCritic(d, n_state, self.chunk_dim, cfg.critic_hidden_dim, cfg.critic_layers, cfg.num_q)
        self.critic_target = copy.deepcopy(self.critic)
        self.critic_target.requires_grad_(False)
        self.bc_flow = FlowVectorField(d, n_state, self.chunk_dim, cfg.hidden_dim, cfg.actor_layers)
        self.onestep = FlowVectorField(d, n_state, self.chunk_dim, cfg.hidden_dim, cfg.actor_layers,
                                       with_time=False)
        self.to(device)

        self.critic_opt = torch.optim.Adam(list(self.critic.parameters()) + list(self.encoder.parameters()),
                                           lr=cfg.lr)
        actor_params = list(self.bc_flow.parameters())
        if cfg.actor_type == "distill-ddpg":
            actor_params += list(self.onestep.parameters())
        self.actor_opt = torch.optim.Adam(actor_params, lr=cfg.lr)

    # ------------------------------------------------------------------ acting
    def compute_flow_actions(self, rgb_feat, state, noise):
        """Euler-integrate the BC flow from noise (t=0) to an action chunk (t=1)."""
        z = self.bc_flow.project(rgb_feat, state)
        a = noise
        n = self.cfg.flow_steps
        for i in range(n):
            t = torch.full((*a.shape[:-1], 1), i / n, device=a.device)
            a = a + self.bc_flow.forward_projected(z, a, t) / n
        return a.clamp(-1, 1)

    @torch.no_grad()
    def sample_from_features(self, rgb_feat, state, deterministic=False):
        """Flattened action chunk [B, h * n_act] in normalised action space. `deterministic` feeds the
        one-step policy zero noise (the mean of its noise input), for evaluation."""
        B = rgb_feat.shape[0]
        if self.cfg.actor_type == "distill-ddpg":
            noise = torch.randn(B, self.chunk_dim, device=rgb_feat.device)
            if deterministic:
                noise.zero_()
            return self.onestep(rgb_feat, state, noise).clamp(-1, 1)
        # best-of-n: draw n flow chunks per obs, keep the one with the highest aggregated Q
        n = self.cfg.actor_num_samples
        noise = torch.randn(B * n, self.chunk_dim, device=rgb_feat.device)
        f, s = rgb_feat.repeat_interleave(n, 0), state.repeat_interleave(n, 0)
        acts = self.compute_flow_actions(f, s, noise)
        qs = self.critic(f, s, acts)
        q = qs.mean(0) if self.cfg.q_agg == "mean" else qs.min(0).values
        best = q.view(B, n).argmax(1)
        return acts.view(B, n, -1)[torch.arange(B, device=q.device), best]

    @torch.no_grad()
    def act(self, rgb, state, deterministic=False):
        """Full chunk [B, horizon, n_act] in normalised action space."""
        chunk = self.sample_from_features(self.encoder(rgb), state, deterministic)
        return chunk.view(-1, self.cfg.horizon, self.n_act)

    # ---------------------------------------------------------------- learning
    def update(self, b, update_actor=True):
        """One gradient step on the critic (+ actor, like acfql's total_loss) from one batch. `b` comes
        from ChunkBuffer.sample (see qc_data.py)."""
        cfg = self.cfg
        B = b["actions"].shape[0]
        actions = b["actions"].reshape(B, -1)

        # ---- critic: h-step TD on the flattened chunk
        feat = self.encoder(b["rgb"])
        with torch.no_grad():
            next_feat = self.encoder(b["next_rgb"])
            next_a = self.sample_from_features(next_feat, b["next_state"])
            nq = self.critic_target(next_feat, b["next_state"], next_a)
            next_q = nq.mean(0) if cfg.q_agg == "mean" else nq.min(0).values
            target = b["rewards"] + (cfg.gamma ** cfg.horizon) * b["masks"] * next_q
        q = self.critic(feat, b["state"], actions)
        critic_loss = (((q - target.unsqueeze(0)) ** 2) * b["critic_valid"].unsqueeze(0)).mean()

        info = dict(critic_loss=critic_loss.detach(), q_mean=q.detach().mean(), q_max=q.detach().max(),
            q_min=q.detach().min(), critic_valid_frac=b["critic_valid"].mean().detach())
        loss = critic_loss
        if update_actor:
            actor_loss, actor_info = self._actor_loss(feat.detach(), b["state"], b["valid"], actions)
            info.update(actor_info)
            loss = loss + actor_loss

        self.critic_opt.zero_grad(set_to_none=True)
        self.actor_opt.zero_grad(set_to_none=True)
        loss.backward()
        self.critic_opt.step()
        if update_actor:
            self.actor_opt.step()
        with torch.no_grad():
            torch._foreach_lerp_(list(self.critic_target.parameters()), list(self.critic.parameters()), cfg.tau)
        return info

    def _actor_loss(self, feat, state, valid, actions):
        cfg = self.cfg
        B = actions.shape[0]

        # flow-matching BC loss on the dataset/replay chunk; only on valid chunk steps
        x0 = torch.randn_like(actions)
        t = torch.rand(B, 1, device=actions.device)
        xt = (1 - t) * x0 + t * actions
        pred = self.bc_flow(feat, state, xt, t)
        bc_loss = (((pred - (actions - x0)) ** 2).view(B, cfg.horizon, self.n_act) * valid.unsqueeze(-1)).mean()

        if cfg.actor_type == "distill-ddpg":
            noise = torch.randn(B, self.chunk_dim, device=actions.device)
            with torch.no_grad():
                target_a = self.compute_flow_actions(feat, state, noise)
            a_pi = self.onestep(feat, state, noise)
            distill = ((a_pi - target_a) ** 2).mean()
            self.critic.requires_grad_(False)  # the Q term only moves the policy, not the critic
            q_loss = -self.critic(feat, state, a_pi.clamp(-1, 1)).mean(0).mean()
            self.critic.requires_grad_(True)
        else:
            distill = q_loss = torch.zeros((), device=actions.device)

        loss = bc_loss + cfg.alpha * distill + q_loss
        return loss, dict(actor_loss=loss.detach(), bc_flow_loss=bc_loss.detach(), distill_loss=distill.detach(),
                          q_loss=q_loss.detach())

    def state_dicts(self):
        return dict(encoder=self.encoder.state_dict(), critic=self.critic.state_dict(),
                    critic_target=self.critic_target.state_dict(), bc_flow=self.bc_flow.state_dict(),
                    onestep=self.onestep.state_dict())

    def load_state_dicts(self, ckpt):
        for k in ("encoder", "critic", "critic_target", "bc_flow", "onestep"):
            getattr(self, k).load_state_dict(ckpt[k])
